### ISSUE TITLE
[Enhancement] MySQL issue

### ISSUE THREAD

**Issue by Yurinann** [ItsWagPvP/SyncCommands#2]
I have observed that after the first start of the plugin (new empty database), the plugin does not automatically build the table when it reads the database for the first time and needs to be restarted again before the "{database_name}.synccommands}" table is created.

Is it possible to create a table at the first connection to the database to avoid redundant restart operations if the condition is established?

Related Information:
```
[16:45:23 WARN]: java.sql.SQLSyntaxErrorException: Table 'hc_synccommand.syncservers' doesn't exist
[16:45:23 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[16:45:23 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[16:45:23 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[16:45:23 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[16:45:23 WARN]:        at SyncCommands-1.1.jar//com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[16:45:23 WARN]:        at SyncCommands-1.1.jar//com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[16:45:23 WARN]:        at SyncCommands-1.1.jar//me.itswagpvp.synccommands.spigot.sync.Register.lambda$getServerList$2(Register.java:72)
[16:45:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:45:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[16:45:23 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[16:45:23 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[16:45:23 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[16:45:23 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[16:45:23 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[16:45:23 INFO]: -> No servers connected...
[16:45:23 INFO]:
[16:45:23 INFO]: -> Loading metrics...
[16:45:23 INFO]:
[16:45:23 INFO]: -> Plugin loaded in 633ms!
[16:45:23 INFO]: +------------------------------------+
```

**Comment by ItsWagPvP** [comment]
Fixing that in 1.2
